### ISSUE TITLE
Adding Additional Details

### ISSUE THREAD

**Issue by strikingraghu** [Contrast-Security-OSS/contrast-java-examples#3]
Hi Team,

I am not able to get an idea about adding below code snippet into pom.xml file.
Where should this be injected? Any specific section of pom.xml?

Configure the existing Maven Cargo Plugin to include Contrast when starting Jetty. Copy the following configuration element to the start-app-before-IT execution:

<configuration>
  <configuration>
    <properties>
      <cargo.jvmargs>
        -javaagent:${project.build.directory}/dependency/contrast-agent.jar
        -Dcontrast.config.path=${user.home}/.contrast.yml
        -Dcontrast.application.name=maven-cargo-how-to
      </cargo.jvmargs>
    </properties>
  </configuration>
</configuration>

**Comment by gilday** [comment]
@strikingraghu you can see an example of where to put this configuration in the `maven-cargo-complete` branch. See https://github.com/Contrast-Security-OSS/contrast-java-examples/blob/maven-cargo-complete/maven-cargo/pom.xml#L89
